#!/usr/bin/env tsx
/**
 * One-time setup helper.
 *
 *  1. Copies env values from ../Retrospect/backend/.env into ./.env
 *     (only the values we need — never overwrites if .env already exists,
 *      unless --force is passed).
 *  2. Tells you what migrations still need to be applied.
 *  3. Tells you what to run next.
 */
import fs from 'fs';
import path from 'path';
import { parseArgs, optBool } from './_args';

const PROJECT_ROOT = path.resolve(__dirname, '..');
const TARGET_ENV = path.join(PROJECT_ROOT, '.env');

// Candidate paths for the source .env (relative to this project root)
const SOURCE_CANDIDATES = [
  path.resolve(PROJECT_ROOT, '..', 'Retrospect', 'backend', '.env'),
  path.resolve(PROJECT_ROOT, '..', '..', 'Projects', 'Retrospect', 'backend', '.env'),
];

const KEYS_TO_COPY = [
  'SUPABASE_URL',
  'SUPABASE_ANON_KEY',
  'SUPABASE_SERVICE_KEY',
  'OPENAI_API_KEY',
  'ANTHROPIC_API_KEY',
  'PERPLEXITY_API_KEY',
  'ELEVENLABS_API_KEY',
  'ELEVENLABS_VOICE_ID',
  'ADMIN_SECRET',
];

function parseEnvFile(filepath: string): Record<string, string> {
  const text = fs.readFileSync(filepath, 'utf-8');
  const out: Record<string, string> = {};
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function findSourceEnv(): string | null {
  for (const candidate of SOURCE_CANDIDATES) {
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

async function main() {
  const args = parseArgs();
  const force = optBool(args, 'force');

  const sourcePath = findSourceEnv();
  if (!sourcePath) {
    console.error('No source .env found. Checked:');
    for (const c of SOURCE_CANDIDATES) console.error(`  - ${c}`);
    console.error('\nCreate .env manually by copying .env.example:');
    console.error('  cp .env.example .env');
    process.exit(1);
  }

  console.log(`Found source: ${sourcePath}`);

  if (fs.existsSync(TARGET_ENV) && !force) {
    console.log(`\n.env already exists at ${TARGET_ENV}`);
    console.log('Pass --force to overwrite.');
    process.exit(0);
  }

  const source = parseEnvFile(sourcePath);

  const lines: string[] = [
    '# Generated by `npm run setup` from ' + sourcePath,
    '# ' + new Date().toISOString(),
    '',
  ];

  let copied = 0;
  let missing: string[] = [];

  for (const key of KEYS_TO_COPY) {
    if (source[key]) {
      lines.push(`${key}=${source[key]}`);
      copied++;
    } else {
      missing.push(key);
    }
  }

  lines.push('');
  lines.push('# Server (override as needed)');
  lines.push('PORT=3001');
  lines.push('NODE_ENV=development');
  lines.push('');
  lines.push('# Models (override as needed)');
  lines.push('OPENAI_CHAT_MODEL=gpt-4o');
  lines.push('OPENAI_EMBEDDING_MODEL=text-embedding-3-large');
  lines.push('');

  fs.writeFileSync(TARGET_ENV, lines.join('\n'));
  console.log(`\nWrote ${TARGET_ENV}`);
  console.log(`  copied: ${copied} key${copied === 1 ? '' : 's'}`);
  if (missing.length > 0) {
    console.log(`  not found in source: ${missing.join(', ')}`);
    console.log('  (These are optional. Set them manually in .env if needed.)');
  }

  console.log('\n----------------------------------------------');
  console.log('NEXT: apply the two migrations in Supabase');
  console.log('----------------------------------------------');
  console.log('Supabase dashboard -> SQL Editor');
  console.log('Run in order:');
  console.log('  1. supabase/migrations/100_agent_extensions.sql');
  console.log('  2. supabase/migrations/101_pipeline_run_traces.sql');
  console.log('\nThen verify everything is wired up:');
  console.log('  npm run doctor');
  console.log('\nThen seed and run:');
  console.log('  npm run seed:demo');
  console.log('  npm run ingest -- --user <demo-id>');
  console.log('  npm run podcast -- --user <demo-id> --skip-tts');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
