-- ============================================
-- 103_user_understanding.sql
-- Append-only versioned User Understanding Document.
-- One latest version per user; older versions kept for diffs / history.
-- Written by Cook 0 after every ingestion run.
-- ============================================

CREATE TABLE IF NOT EXISTS user_understanding (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Monotonic per-user version. Append-only — never updated in place.
    version INTEGER NOT NULL,

    -- The hybrid structured document.
    -- Top-level keys are fixed; values are prose. emerging_dimensions lets
    -- Cook 0 invent new identity categories that don't fit the defaults.
    document JSONB NOT NULL,

    -- Snapshot of inference ids active at this version (for traceability)
    inference_ids_at_version UUID[] DEFAULT '{}',

    -- What Cook 0 did vs the previous version (added/promoted/retired/rewrote)
    generation_notes TEXT,

    -- Which ingestion run produced this version
    source_ingestion_run_id UUID REFERENCES pipeline_run_traces(id) ON DELETE SET NULL,

    -- Generated by which model (e.g. "claude-opus-4-7")
    model TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Unique (user_id, version) — supports optimistic concurrency: two parallel
-- ingests on the same user will both try to insert v=N+1; one wins, the other
-- retries with a fresh read of the current max version.
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_understanding_user_version
    ON user_understanding(user_id, version);

-- Fast "give me the latest version for this user"
CREATE INDEX IF NOT EXISTS idx_user_understanding_user_latest
    ON user_understanding(user_id, version DESC);

CREATE INDEX IF NOT EXISTS idx_user_understanding_run
    ON user_understanding(source_ingestion_run_id);

-- ------------------------------------------------------------
-- RLS
-- ------------------------------------------------------------
ALTER TABLE user_understanding ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own understanding" ON user_understanding
    FOR SELECT USING (user_id = auth.uid());

-- Insert is service-role only (Cook 0 only writes via service key).
-- No update/delete policies — append-only by design.
